import re

from app.schemas.chat import Category

# Lowercase substrings, multilingual (pt/es/en/fr/de/it). Order = priority.
CATEGORY_KEYWORDS: dict[str, tuple[str, ...]] = {
    "nationality": (
        "nationality",
        "nacionalidade",
        "nacionalidad",
        "nationalité",
        "nationalit",
        "nazionalit",
        "grandmother",
        "grandfather",
        "avó",
        "avô",
        "abuela",
        "abuelo",
    ),
    "citizenship": (
        "citizen",
        "cidadania",
        "ciudadan",
        "citoyenn",
        "staatsbürger",
        "cittadinanza",
        "passport",
        "passaporte",
        "pasaporte",
    ),
    "residency": ("residen", "residên", "résidence", "aufenthalt", "residenza", "visa", "visto"),
    "immigration": (
        "immigra",
        "migra",
        "inmigra",
        "emigr",
        "mudar",
        "mudarme",
        "move to",
        "moving to",
        "relocat",
        "mudança",
        "mudanza",
        "mudarse",
        "déménag",
        "umzug",
        "trasfer",
    ),
    "documents": (
        "document",
        "apostill",
        "certificate",
        "certidão",
        "certificado",
        "cédula",
        "cedula",
        "birth cert",
        "antecedentes",
        "paperwork",
        "casier",
    ),
    "cities": (
        "montevideo",
        "punta del este",
        "colonia",
        "maldonado",
        "salto",
        "paysandú",
        "rocha",
        "piriápolis",
        "city",
        "cities",
        "cidade",
        "ciudad",
        "ville",
        "stadt",
        "città",
        "neighborhood",
        "barrio",
        "bairro",
    ),
    "cost_of_living": (
        "cost of living",
        "custo de vida",
        "costo de vida",
        "coût de la vie",
        "lebenshaltung",
        "costo della vita",
        "how much",
        "quanto custa",
        "cuánto cuesta",
        "expensive",
        "caro",
        "price",
        "preço",
        "precio",
        "budget",
        "salary",
        "salário",
    ),
    "banking": (
        "bank",
        "banco",
        "banque",
        "bancario",
        "account",
        "conta",
        "cuenta",
        "wire",
        "transfer",
        "pix",
        "credit card",
    ),
    "education": (
        "school",
        "escola",
        "escuela",
        "university",
        "universidade",
        "universidad",
        "udelar",
        "education",
        "educação",
        "educación",
        "école",
        "schule",
        "scuola",
        "study",
        "estudar",
        "estudiar",
    ),
    "employment": (
        "job",
        "work",
        "trabalho",
        "trabajo",
        "employ",
        "emprego",
        "empleo",
        "travail",
        "arbeit",
        "lavoro",
        "remote",
        "freelanc",
        "salary",
    ),
    "healthcare": (
        "health",
        "saúde",
        "salud",
        "santé",
        "gesundheit",
        "salute",
        "hospital",
        "mutualista",
        "fonasa",
        "doctor",
        "médico",
        "insurance",
        "seguro",
    ),
    "taxes": ("tax", "imposto", "impuesto", "impôt", "steuer", "tasse", "irpf", "dgi", "bps"),
    "transport": (
        "transport",
        "bus",
        "ônibus",
        "ómnibus",
        "car ",
        "carro",
        "auto",
        "train",
        "tren",
        "flight",
        "voo",
        "vuelo",
        "driver",
        "licen",
        "carnet de conducir",
        "stm",
    ),
    "housing": (
        "housing",
        "rent",
        "aluguel",
        "alquiler",
        "apartment",
        "apartamento",
        "house",
        "casa",
        "buy a home",
        "comprar",
        "loyer",
        "miete",
        "affitto",
        "property",
        "inmueble",
    ),
    "culture": (
        "culture",
        "cultura",
        "mate",
        "candombe",
        "carnival",
        "carnaval",
        "tradition",
        "tradição",
        "tradición",
        "football",
        "futebol",
        "fútbol",
        "asado",
        "chivito",
        "language",
        "idioma",
        "curiosit",
        "food",
        "comida",
    ),
}

GENERAL_KEYWORDS = (
    "uruguay",
    "uruguai",
    "uruguayo",
    "uruguaio",
    "uruguayen",
    "uruguaiano",
    "uruguayan",
    "uruguayo",
)

# Only used when nothing above matched.
UNRELATED_KEYWORDS = (
    "malware",
    "ransomware",
    "virus",
    "hack",
    "exploit",
    "keylogger",
    "quantum",
    "physics",
    "chemistry",
    "calculus",
    "theorem",
    "poem",
    "poema",
    "poesia",
    "poésie",
    "gedicht",
    "song lyrics",
    "story about",
    "write me a",
    "python",
    "javascript",
    "java",
    "sql",
    "regex",
    "code",
    "código",
    "programa",
    "bitcoin",
    "stock",
    "crypto",
    "horoscope",
    "recipe for",
    "joke",
    "piada",
    "chiste",
    "homework",
    "essay",
    "mars",
    "marte",
    "politician",
    "president of the united",
    "ignore previous",
    "ignore all previous",
    "system prompt",
    "jailbreak",
)

OUT_OF_SCOPE_REPLY = {
    "pt-BR": "Este assistente é focado no Uruguai, na mudança para o país e na vida no Uruguai.",
    "es": "Este asistente está enfocado en Uruguay, la mudanza al país y la vida en Uruguay.",
    "en": "This assistant is focused on Uruguay, relocation and life in Uruguay.",
    "fr": "Cet assistant se concentre sur l'Uruguay, le déménagement et la vie en Uruguay.",
    "de": "Dieser Assistent konzentriert sich auf Uruguay, den Umzug dorthin und das Leben in Uruguay.",
    "it": "Questo assistente è dedicato all'Uruguay, al trasferimento e alla vita in Uruguay.",
}


def _find(text: str, keywords: tuple[str, ...]) -> bool:
    """True if any keyword occurs at the start of a word (so 'mate' won't match 'climate')."""
    return any(re.search(rf"\b{re.escape(k.strip())}", text) for k in keywords)


def classify(message: str) -> Category:
    """Cheap keyword scope check. Lenient: unknown short/ambiguous text goes to the LLM."""
    text = re.sub(r"\s+", " ", message.lower())
    for category, keywords in CATEGORY_KEYWORDS.items():
        if _find(text, keywords):
            return category  # type: ignore[return-value]
    if _find(text, GENERAL_KEYWORDS):
        return "general_uruguay"
    if _find(text, UNRELATED_KEYWORDS):
        return "out_of_scope"
    return "general_uruguay"
